// Callout positions for CS2 maps
// Coordinates are percentages (0-100) relative to the radar image
// Source: csnades.gg (Mirage), standard CS2 radar layouts (others)

export const CALLOUTS: Record<string, Array<{ name: string; x: number; y: number }>> = {
  mirage: [
    { name: 'Window', x: 37, y: 44 },
    { name: 'Jungle', x: 38, y: 65 },
    { name: 'Connector', x: 49, y: 55 },
    { name: 'Stairs', x: 52, y: 68 },
    { name: 'Palace', x: 69, y: 90 },
    { name: 'A Site', x: 55, y: 84 },
    { name: 'B Site', x: 15, y: 25 },
    { name: 'B Apartments', x: 30, y: 7 },
    { name: 'Mid', x: 53, y: 45 },
    { name: 'Top Mid', x: 71, y: 39 },
    { name: 'T Spawn', x: 80, y: 45 },
    { name: 'CT Spawn', x: 33, y: 90 },
    { name: 'A Ramp', x: 75, y: 71 },
    { name: 'Kitchen', x: 39, y: 15 },
    { name: 'Market', x: 15, y: 42 },
    { name: 'Catwalk', x: 52, y: 38 },
    { name: 'Tetris', x: 62, y: 66 },
    { name: 'Triple', x: 50, y: 83 },
    { name: 'Sandwich', x: 57, y: 69 },
  ],
  inferno: [
    { name: 'T Spawn', x: 10, y: 68 },
    { name: 'CT Spawn', x: 89, y: 35 },
    { name: 'A Site', x: 82, y: 70 },
    { name: 'B Site', x: 51, y: 22 },
    { name: 'Banana', x: 47, y: 43 },
    { name: 'Mid', x: 44, y: 65 },
    { name: 'Second Mid', x: 52, y: 79 },
    { name: 'Arch', x: 78, y: 51 },
    { name: 'Library', x: 90, y: 55 },
    { name: 'Apartments', x: 75, y: 83 },
    { name: 'Pit', x: 92, y: 81 },
    { name: 'Coffins', x: 52, y: 15 },
    { name: 'CT', x: 89, y: 31 },
    { name: 'Moto', x: 89, y: 69 },
    { name: 'Top Banana', x: 47, y: 35 },
    { name: 'Bottom Banana', x: 42, y: 52 },
    { name: 'Graveyard', x: 78, y: 64 },
    { name: 'Balcony', x: 76, y: 77 },
    { name: 'Short', x: 72, y: 62 },
    { name: 'Ruins', x: 67, y: 52 },
    { name: 'T Ramp', x: 20, y: 63 },
    { name: 'Alt Mid', x: 30, y: 73 },
    { name: 'Fountain', x: 60, y: 18 },
    { name: 'Dark', x: 42, y: 25 },
    { name: 'Construction', x: 56, y: 25 },
    { name: 'New Box', x: 46, y: 17 },
    { name: 'First Oranges', x: 43, y: 27 },
    { name: 'Boiler', x: 68, y: 69 },
  ],
  dust2: [
    { name: 'T Spawn', x: 40, y: 90 },
    { name: 'CT Spawn', x: 59, y: 20 },
    { name: 'A Site', x: 80, y: 17 },
    { name: 'A Platform', x: 70, y: 14 },
    { name: 'B Site', x: 20, y: 14 },
    { name: 'Long', x: 86, y: 39 },
    { name: 'Long Doors', x: 69, y: 55 },
    { name: 'A Long', x: 87, y: 30 },
    { name: 'Mid', x: 46, y: 51 },
    { name: 'Xbox', x: 48, y: 40 },
    { name: 'Short', x: 56, y: 30 },
    { name: 'Catwalk', x: 62, y: 22 },
    { name: 'Upper Tunnels', x: 17, y: 47 },
    { name: 'B Tunnels', x: 32, y: 41 },
    { name: 'B Doors', x: 26, y: 23 },
    { name: 'CT Mid Doors', x: 33, y: 32 },
    { name: 'A Car', x: 88, y: 22 },
    { name: 'Goose', x: 76, y: 12 },
    { name: 'Pit', x: 92, y: 35 },
    { name: 'Outside Long', x: 76, y: 65 },
    { name: 'T Mid', x: 40, y: 65 },
    { name: 'Suicide', x: 47, y: 70 },
    { name: 'B Window', x: 22, y: 20 },
    { name: 'B Plat', x: 16, y: 18 },
    { name: 'Close', x: 28, y: 14 },
    { name: 'Back Plat', x: 15, y: 12 },
  ],
  nuke: [
    { name: 'T Spawn', x: 23, y: 55 },
    { name: 'T Roof', x: 46, y: 56 },
    { name: 'CT Spawn', x: 82, y: 46 },
    { name: 'A Site', x: 58, y: 52 },
    { name: 'B Site', x: 58, y: 57 },
    { name: 'Outside', x: 53, y: 72 },
    { name: 'Lobby', x: 47, y: 54 },
    { name: 'Ramp', x: 50, y: 40 },
    { name: 'Heaven', x: 62, y: 46 },
    { name: 'Vent', x: 54, y: 61 },
    { name: 'Vent Room', x: 61, y: 61 },
    { name: 'Mini', x: 57, y: 64 },
    { name: 'Hut', x: 54, y: 55 },
    { name: 'Silo', x: 60, y: 70 },
    { name: 'Secret', x: 70, y: 57 },
    { name: 'Garage', x: 38, y: 72 },
    { name: 'Radio', x: 72, y: 42 },
    { name: 'Trophy', x: 69, y: 50 },
    { name: 'Control Room', x: 65, y: 42 },
    { name: 'Squeaky', x: 52, y: 50 },
    { name: 'Main', x: 55, y: 47 },
    { name: 'Yard', x: 48, y: 66 },
  ],
  anubis: [
    { name: 'T Spawn', x: 38, y: 88 },
    { name: 'CT Spawn', x: 38, y: 22 },
    { name: 'A Site', x: 78, y: 22 },
    { name: 'B Site', x: 35, y: 48 },
    { name: 'A Main', x: 81, y: 45 },
    { name: 'A Main Connector', x: 63, y: 38 },
    { name: 'B Main', x: 25, y: 62 },
    { name: 'Mid', x: 57, y: 41 },
    { name: 'CT Mid', x: 48, y: 31 },
    { name: 'Bridge', x: 50, y: 58 },
    { name: 'Canal', x: 57, y: 59 },
    { name: 'Palace', x: 72, y: 32 },
    { name: 'Alley', x: 86, y: 35 },
    { name: 'Water', x: 50, y: 50 },
    { name: 'Connector', x: 63, y: 30 },
    { name: 'Ruins', x: 28, y: 52 },
    { name: 'T Street', x: 45, y: 75 },
    { name: 'Boat', x: 52, y: 66 },
    { name: 'Walkway', x: 38, y: 38 },
    { name: 'Heaven', x: 78, y: 18 },
    { name: 'Pillar', x: 35, y: 42 },
  ],
  ancient: [
    { name: 'T Spawn', x: 48, y: 87 },
    { name: 'CT Spawn', x: 50, y: 12 },
    { name: 'CT Area', x: 62, y: 25 },
    { name: 'A Site', x: 21, y: 27 },
    { name: 'B Site', x: 76, y: 40 },
    { name: 'A Main', x: 17, y: 40 },
    { name: 'B Ramp', x: 83, y: 52 },
    { name: 'Mid', x: 47, y: 36 },
    { name: 'Donut', x: 34, y: 46 },
    { name: 'Cave', x: 62, y: 53 },
    { name: 'Elbow', x: 22, y: 52 },
    { name: 'Temple', x: 30, y: 30 },
    { name: 'A Drop', x: 25, y: 35 },
    { name: 'B Halls', x: 70, y: 50 },
    { name: 'Water', x: 48, y: 55 },
    { name: 'Side Path', x: 38, y: 58 },
    { name: 'House', x: 54, y: 44 },
    { name: 'Jaguar', x: 16, y: 25 },
    { name: 'CT B', x: 70, y: 30 },
    { name: 'B Main', x: 80, y: 60 },
  ],
  overpass: [
    { name: 'T Spawn', x: 68, y: 91 },
    { name: 'CT Spawn', x: 48, y: 18 },
    { name: 'A Site', x: 45, y: 22 },
    { name: 'B Site', x: 69, y: 32 },
    { name: 'A Long', x: 19, y: 45 },
    { name: 'B Short', x: 72, y: 42 },
    { name: 'Monster', x: 81, y: 44 },
    { name: 'Mid', x: 39, y: 62 },
    { name: 'Bathrooms', x: 29, y: 50 },
    { name: 'Bank', x: 44, y: 11 },
    { name: 'Heaven', x: 58, y: 24 },
    { name: 'Barrels', x: 75, y: 25 },
    { name: 'Connector', x: 55, y: 38 },
    { name: 'Playground', x: 32, y: 35 },
    { name: 'Fountain', x: 48, y: 55 },
    { name: 'Party', x: 63, y: 48 },
    { name: 'Water', x: 78, y: 38 },
    { name: 'Tunnels', x: 82, y: 55 },
    { name: 'Stairs', x: 35, y: 40 },
    { name: 'Truck', x: 40, y: 28 },
    { name: 'Graffiti', x: 76, y: 54 },
    { name: 'Construction', x: 67, y: 22 },
  ],
}
